// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUemxbHWe9AtO2sn2rLnCg9nFnOtb2bNU',
    appId: '1:654442201741:web:fe00f8c207f11d927018c4',
    messagingSenderId: '654442201741',
    projectId: 'mstore-f7aac',
    authDomain: 'mstore-f7aac.firebaseapp.com',
    storageBucket: 'mstore-f7aac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3U64WqJAaNmUEfsWX6y4LEqJiity7jk',
    appId: '1:654442201741:android:61937da05c752c007018c4',
    messagingSenderId: '654442201741',
    projectId: 'mstore-f7aac',
    storageBucket: 'mstore-f7aac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPYKXy1RjpluPfqycVdFxNKMUxHS-qUg',
    appId: '1:654442201741:ios:508dfa2618d20da17018c4',
    messagingSenderId: '654442201741',
    projectId: 'mstore-f7aac',
    storageBucket: 'mstore-f7aac.appspot.com',
    androidClientId: '654442201741-iug44kgmp23gilqh16q5ijfqbvms6mii.apps.googleusercontent.com',
    iosClientId: '654442201741-2f6v38qif3uu0plfnrlio40mc0fgpglj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPYKXy1RjpluPfqycVdFxNKMUxHS-qUg',
    appId: '1:654442201741:ios:508dfa2618d20da17018c4',
    messagingSenderId: '654442201741',
    projectId: 'mstore-f7aac',
    storageBucket: 'mstore-f7aac.appspot.com',
    androidClientId: '654442201741-iug44kgmp23gilqh16q5ijfqbvms6mii.apps.googleusercontent.com',
    iosClientId: '654442201741-2f6v38qif3uu0plfnrlio40mc0fgpglj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUemxbHWe9AtO2sn2rLnCg9nFnOtb2bNU',
    appId: '1:654442201741:web:e3d54c90e07f43c57018c4',
    messagingSenderId: '654442201741',
    projectId: 'mstore-f7aac',
    authDomain: 'mstore-f7aac.firebaseapp.com',
    storageBucket: 'mstore-f7aac.appspot.com',
  );

}